version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    transaction:
        format: "%(asctime)s - %(message)s"
        datefmt: '%Y-%m-%d %H:%M'

handlers:
    transaction:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: transaction
        filename: ../../../resources/transactions.log
        maxBytes: 1048576
    errors:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ../../../resources/error.log
        maxBytes: 1048576

    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

root:
    #Change this value only to change your whole application top logging LEVEL
    level: DEBUG
    handlers: [console, transaction, errors]